# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inventory.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finventory.proto\x12\tinventory\"J\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x10\n\x08quantity\x18\x04 \x01(\x05\"3\n\x0cInventoryReq\x12\x11\n\tproductId\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"5\n\x11InventoryResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xf9\x02\n\x10InventoryService\x12@\n\nAddProduct\x12\x12.inventory.Product\x1a\x1c.inventory.InventoryResponse\"\x00\x12H\n\rRemoveProduct\x12\x17.inventory.InventoryReq\x1a\x1c.inventory.InventoryResponse\"\x00\x12\x43\n\rUpdateProduct\x12\x12.inventory.Product\x1a\x1c.inventory.InventoryResponse\"\x00\x12I\n\x0e\x43heckInventory\x12\x17.inventory.InventoryReq\x1a\x1c.inventory.InventoryResponse\"\x00\x12I\n\x0eReserveProduct\x12\x17.inventory.InventoryReq\x1a\x1c.inventory.InventoryResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PRODUCT']._serialized_start=30
  _globals['_PRODUCT']._serialized_end=104
  _globals['_INVENTORYREQ']._serialized_start=106
  _globals['_INVENTORYREQ']._serialized_end=157
  _globals['_INVENTORYRESPONSE']._serialized_start=159
  _globals['_INVENTORYRESPONSE']._serialized_end=212
  _globals['_INVENTORYSERVICE']._serialized_start=215
  _globals['_INVENTORYSERVICE']._serialized_end=592
# @@protoc_insertion_point(module_scope)
